version: 2
jobs:
  test:
    docker:
      - image: golangci/golangci-lint:v1.26.0
    working_directory: ~/app
    steps:
      - checkout
      - run: go get github.com/stretchr/testify
      - run: golangci-lint run .
      - run: |
          if [ `gofmt -l .` ]; then
            echo "you must run 'go fmt' to fix formatting"
            exit 1
          fi
      - run: go test
  deploy:
    docker:
      - image: docker:19.03.8
    working_directory: ~/app
    steps:
      - checkout
      - run: docker build -t registry.dev.brainhub.pl/issue-label-bot/main .
      - run: docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD https://registry.dev.brainhub.pl
      - run: docker push registry.dev.brainhub.pl/issue-label-bot/main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
