version: 2
jobs:
  test:
    docker:
      - image: golangci/golangci-lint:v1.26.0
    working_directory: ~/app
    steps:
      - checkout
      - run: go get github.com/stretchr/testify
      - run: golangci-lint run ./...
      - run: |
          if [ `gofmt -l . | head -1` ]; then
            echo "you must run 'go fmt ./...' to fix formatting"
            exit 1
          fi
      - run: go test ./...
  deploy_docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t brainhubeu/issue-label-bot .
      - run: docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
      - run: docker push brainhubeu/issue-label-bot
  deploy_rancher:
    docker:
      - image: kiwicom/crane:3.2.1
    steps:
      - run: crane --stack issue-label-bot --service issue-label-bot-main --url $RANCHER_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --env 1a5

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_docker:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_rancher:
          requires:
            - deploy_docker
