version: 2
jobs:
  test:
    docker:
      - image: golangci/golangci-lint:v1.26.0
    working_directory: ~/app
    steps:
      - checkout
      - run: go get github.com/stretchr/testify
      - run: golangci-lint run ./...
      - run: |
          if [ `gofmt -l . | head -1` ]; then
            echo "you must run 'go fmt ./...' to fix formatting"
            exit 1
          fi
      - run: go test ./...
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t brainhubeu/issue-label-bot .
      - run: docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
      - run: docker push brainhubeu/issue-label-bot

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
