version: 2.1
executors:
  go-executor:
    docker:
      - image: golangci/golangci-lint:v1.26.0
    working_directory: ~/app
jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go get github.com/onsi/gomega/...
      - run: go get golang.org/x/tools/cmd/cover
      - run: golangci-lint run ./...
      - run: |
          if [ `gofmt -l . | head -1` ]; then
            echo "you must run 'go fmt ./...' to fix formatting"
            exit 1
          fi
      - run: go test -v -coverprofile cover.html ./...
      - run: apt-get update
      - run: apt-get install shellcheck
      - run: shellcheck *.sh
      - persist_to_workspace:
          root: ~/app
          paths:
            - .git
            - cover.html
  upload_coverage:
    executor: go-executor
    steps:
      - attach_workspace:
          at: ~/app
      - run: git checkout .
      - run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN" -f cover.html
  deploy_docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t brainhubeu/issue-overseer:latest .
      - run: docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
      - run: docker push brainhubeu/issue-overseer:latest
  deploy_rancher:
    working_directory: ~/app
    docker:
      - image: curlimages/curl:7.70.0
    steps:
      - run: |
          curl -i --fail "$RANCHER_URL/v1/projects/$RANCHER_PROJECT_ID/services/$RANCHER_SERVICE_ID/?action=upgrade" \
            -H 'content-type: application/json' \
            -u "$RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY" \
            --data-binary '{"inServiceStrategy":{"launchConfig":{"environment":{"GITHUB_TOKEN":"'"$GITHUB_TOKEN"'","GITHUB_ORGANIZATION":"'"$GITHUB_ORGANIZATION"'"},"imageUuid":"docker:brainhubeu/issue-overseer:latest","labels":{"io.rancher.container.pull_image":"always"}}}}' \
            --compressed
          sleep 60
          curl -i --fail "$RANCHER_URL/v1/projects/$RANCHER_PROJECT_ID/services/$RANCHER_SERVICE_ID/?action=finishupgrade" \
            -X 'POST' \
            -H 'content-type: application/json' \
            -H 'sec-fetch-dest: empty' \
            -u "$RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY" \
            --compressed

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - upload_coverage:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_docker:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_rancher:
          requires:
            - deploy_docker
